TensorFlow 的基本運算單位是張量（Tensor），零維張量等於是純量(Scalar)，一維張量是向量(Vector)，二維張量是矩陣(Matrix)等等。和Numpy相對比，ndarray（n 維陣列）觀念與 Tensor（n 維張量）觀念類似以外，TensorFlow 函數的命名、參數與設計概念都很接近 NumPy。

複習一下Tensorflow主要的運作流程分為以下兩個部分
* 建立模型(Build Model)
* 執行運算(Run)

Tensorflow設計的核心就是Tensor的流動，建立Graph的過程其實只是定義好Tensor如何流動並運算的過程，但真正的資料其實並沒有被運算，真正的計算需要用session來執行。
![graph](https://www.tensorflow.org/images/tensors_flowing.gif)

In [4]:
%matplotlib inline

In [5]:
import numpy as np
import tensorflow as tf
import pandas as pd
from matplotlib import pyplot as plt

# What is tensor?

In [6]:
one_d_arr = np.arange(24)
two_d_arr = np.arange(24).reshape(6, 4)
three_d_arr = np.arange(24).reshape(2, 3, 4)

print("Python:")
print(one_d_arr.ndim)
print(two_d_arr.ndim)
print(three_d_arr.ndim)

Python:
1
2
3


In [7]:
one_d_tensor = tf.constant(np.arange(24))
two_d_tensor = tf.constant(np.arange(24), shape=(6, 4))
three_d_tensor = tf.constant(np.arange(24), shape=(2, 3, 4))

print("TensorFlow:")
print(len(one_d_tensor.get_shape()))
print(len(two_d_tensor.get_shape()))
print(len(three_d_tensor.get_shape()))

TensorFlow:
1
2
3


In [8]:
hw = tf.constant("Hello World")
with tf.Session() as sess:
    print(sess.run(hw))

b'Hello World'


In [9]:
# Build a dataflow graph.
c = tf.constant([[1.0, 2.0], [3.0, 4.0]])
d = tf.constant([[1.0, 1.0], [0.0, 1.0]])
e = tf.matmul(c, d)

# Construct a `Session` to execute the graph.
with tf.Session() as sess:
  # Execute the graph and store the value that `e` represents in `result`.
  result = sess.run(e)

print(result)

[[1. 3.]
 [3. 7.]]


Tensor可以被宣告為常數（Constant）、變數（Variable）或者 佔位符(Placeholder) 這三種類型。

# 常數（Constant）

In [10]:
#In Python, constants are written in all capital letters
print("Python:")
A = 19
B = 3
print(A + B)
print(A - B)
print(A * B)
print(A / B)
print(A** B)
print(A % B)
print(A// B)

Python:
22
16
57
6.333333333333333
6859
1
6


Tensor數值運算這些函數都必須在 TensorFlow 的 Session 中執行才會有運算結果的輸出，否則只是顯示張量物件的資訊而已。

* 加 +：tf.add()
* 減 -： tf.sub()
* 乘 *： tf.multiply()
* 除 /： tf.divide()
* 次方 **： tf.pow()
* 求餘數 %： tf.mod()
* 求商數 //：tf.div()

In [11]:
x = tf.constant(19)
y = tf.constant(3)

print("TensorFlow:")
print( tf.add(x, y) )
print( tf.subtract(x, y) )
print( tf.multiply(x, y) )
print( tf.divide(x, y) )
print( tf.pow(x, y) )
print( tf.mod(x, y) )
print( tf.div(x, y) )

TensorFlow:
Tensor("Add:0", shape=(), dtype=int32)
Tensor("Sub:0", shape=(), dtype=int32)
Tensor("Mul:0", shape=(), dtype=int32)
Tensor("truediv:0", shape=(), dtype=float64)
Tensor("Pow:0", shape=(), dtype=int32)
Tensor("FloorMod:0", shape=(), dtype=int32)
Tensor("div:0", shape=(), dtype=int32)


一個 Tensor的運算需要三個步驟：

1. 宣告張量
2. 使用張量的運算公式
3. 在 Session 裡執行運算

In [12]:
with tf.Session() as sess:
    print( sess.run(tf.add(x, y)) )
    print( sess.run(tf.subtract(x, y)) )
    print( sess.run(tf.multiply(x, y)) )
    print( sess.run(tf.divide(x, y)) )
    print( sess.run(tf.pow(x, y)) )
    print( sess.run(tf.mod(x, y)) )
    print( sess.run(tf.div(x, y)) )

22
16
57
6.333333333333333
6859
1
6


In [13]:
#使用運算符號也可以，但也是要記得在 Session 中執行。
with tf.Session() as sess:
    print( sess.run(x + y) )
    print( sess.run(x - y) )
    print( sess.run(x * y) )
    print( sess.run(x / y) )
    print( sess.run(x**y) )
    print( sess.run(x % y) )
    print( sess.run(x // y) )

22
16
57
6.333333333333333
6859
1
6


In [14]:
isess = tf.InteractiveSession()

print("Interactive Session:")
print( tf.add(x, y).eval() )
print( tf.subtract(x, y).eval() )
print( tf.multiply(x, y).eval() )
print( tf.divide(x, y).eval() )
print( tf.pow(x, y).eval() )
print( tf.mod(x, y).eval() )
print( tf.div(x, y).eval() )

isess.close()

Interactive Session:
22
16
57
6.333333333333333
6859
1
6


常用的常數張量建構函數有:
* tf.zeros() ：建構內容數值皆為 0 的常數向量
* tf.ones() ：建構內容數值皆為 1 的常數向量
* tf.fill() ：建構內容數值皆為特定值的常數向量
* tf.range() ：建構內容數值為 (start, limit, delta) 數列的常數向量
* tf.random_normal() ：建構內容數值為符合常態分佈數列的常數向量
* tf.random_uniform() ：建構內容數值為符合均勻分佈數列的常數向量

常用的矩陣運算函數有:
* tf.reshape() ：調整矩陣外觀
* tf.eye() ：建構單位矩陣
* tf.diag() ：建構對角矩陣
* tf.matrix_transpose() ：轉置矩陣
* tf.matmul() ：矩陣相乘

In [15]:
print("NumPy:")
print(np.zeros((2, 2)))
print(np.ones((2, 2)))
print(np.full((2, 2), 5))
print(np.arange(1, 9, 2).reshape(2, 2))
print(np.random.normal(size=(2, 2)))
print(np.random.uniform(size=(2, 2)))

print(np.eye(2))
print(np.diag(np.arange(4)))
print(np.ones((2, 3)).T)
print(np.dot(np.arange(4).reshape(2, 2), np.arange(4).reshape(2, 2)))

NumPy:
[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[5 5]
 [5 5]]
[[1 3]
 [5 7]]
[[-0.707008   -0.52875076]
 [ 0.44092994  1.92858202]]
[[0.35095293 0.53890325]
 [0.06470914 0.919516  ]]
[[1. 0.]
 [0. 1.]]
[[0 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[ 2  3]
 [ 6 11]]


In [16]:
print("TensorFlow:")
zeros = tf.zeros((2, 2))
ones = tf.ones((2, 2))
fills = tf.fill((2, 2), 5)
ranges = tf.reshape(tf.range(1, 9, 2), (2, 2))
normals = tf.random_normal((2, 2))
uniforms = tf.random_uniform((2, 2))
eye = tf.eye(2)
diag = tf.diag(tf.range(4))
transpose = tf.matrix_transpose(tf.ones((2, 3)))
x = tf.reshape(tf.range(4), (2, 2))
multiply = tf.matmul(x, x)
matrice = [eye, diag, transpose, multiply]
initializations = [zeros, ones, fills, ranges, normals, uniforms, eye, diag, transpose, multiply]

with tf.Session() as sess:
    for i in initializations:
        print(sess.run(i))

TensorFlow:
[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[5 5]
 [5 5]]
[[1 3]
 [5 7]]
[[-3.0080996   0.02691678]
 [-0.4987872   1.1137937 ]]
[[0.56783473 0.19176853]
 [0.4971304  0.00339484]]
[[1. 0.]
 [0. 1.]]
[[0 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[ 2  3]
 [ 6 11]]


# 變數（Variable）

程式設計中為了保持彈性，必須將值賦與給變數（Variables），讓使用者能夠動態地進行相同的計算來得到不同的結果，這在 TensorFlow 中是以 tf.Variable() 來完成。

但宣告變數張量並不如 Python 或者先前宣告常數張量那麼單純，它需要兩個步驟：

1. 宣告變數張量的初始值、類型與外觀
2. 初始化變數張量

In [17]:
var_py = 47
print("Python:")
print(var_py)

Python:
47


In [18]:
# TensorFlow: FailedPreconditionError
var_tf = tf.Variable(47)
print("TensorFlow:")
with tf.Session() as sess:
    print(sess.run(var_tf))

TensorFlow:


FailedPreconditionError: Attempting to use uninitialized value Variable
	 [[{{node _retval_Variable_0_0}} = _Retval[T=DT_INT32, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Variable)]]

In [19]:
var_tf = tf.Variable(47)
print("TensorFlow:")
with tf.Session() as sess:
    sess.run(var_tf.initializer)
    print(sess.run(var_tf))

TensorFlow:
47


初始化成功後的變數張量，可以透過 .assign() 方法重新賦予不同值。

重新賦値這件事對 TensorFlow 來說也是一個運算，必須在宣告之後放入 Session 中執行，否則重新賦值並不會有作用。

重新賦值時必須要注意類型，賦予不同類型的值會得到 TypeError。

不僅是值的類型，外觀也必須跟當初所宣告的相同，賦予不同外觀的值會得到 ValueError。

In [20]:
var_tf = tf.Variable(47)
assign_op = var_tf.assign(24)

print("TensorFlow:")
with tf.Session() as sess:
    sess.run(var_tf.initializer)
    print('Before assign',sess.run(var_tf))
    #sess.run(assign_op)
    print('After assign',sess.run(var_tf))

TensorFlow:
Before assign 47
After assign 47


In [21]:
var_tf = tf.Variable(np.ones([3, 4]))
#assign_op = var_tf.assign(24)
assign_op = var_tf.assign(np.arange(12).reshape(3, 4))

print("TensorFlow:")
with tf.Session() as sess:
    sess.run(var_tf.initializer)
    print('Before assign',sess.run(var_tf))
    sess.run(assign_op)
    print('After assign',sess.run(var_tf))

TensorFlow:
Before assign [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
After assign [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


# 佔位符(Placeholder)

在Tensorflow中我們都是先建好Graph再決定資料的input與output，在上面的例子由於我們已經先定義好constant Tensor所以並不需要給Graph任何Input我們就可以得到各種張量運算的output，但如果我們操作的不是常數張量呢?

這時候我們就需要Placeholder來幫助我們在還沒有資料的時候先佔個位子，這是一種常見將資料輸入 TensorFlow 計算圖形（Graph）的方法。

Placeholder 張量和變數張量一樣，必須預先定義好之後欲輸入的資料類型與外觀。使用 tf.placeholder() 可以建出 Placeholder 張量。

宣告完 Placeholder 以後，TensorFlow 資料輸入placeholder的術語稱作是 Feed dictionaries，顧名思義就是將資料以 Python dictionaries 餵進（Feed）Placeholder 張量之中。

In [22]:
p1 = tf.placeholder(tf.float32, shape=(4,))
p2 = tf.placeholder(tf.float32, shape=(4,))

print(p1,p2)
add_op = p1 + p2
print(add_op)
with tf.Session() as sess:
    adder=sess.run(add_op, feed_dict={p1: [7, 14, 21, 28], p2: [5, 10, 15, 20]})
    print(adder)

Tensor("Placeholder:0", shape=(4,), dtype=float32) Tensor("Placeholder_1:0", shape=(4,), dtype=float32)
Tensor("add_4:0", shape=(4,), dtype=float32)
[12. 24. 36. 48.]
